/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicantMain: typeof import('./src/components/page/Manage-user/ApplicantMain.vue')['default']
    ApplicantModal: typeof import('./src/components/page/Manage-user/ApplicantModal.vue')['default']
    ApplicantSearch: typeof import('./src/components/page/Manage-user/ApplicantSearch.vue')['default']
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    copy: typeof import('./src/components/page/Board/Notice/FirstNoticeMain copy.vue')['default']
    FirstNoticeDetail: typeof import('./src/components/page/Board/Notice/FirstNoticeDetail.vue')['default']
    'FirstNoticeDetail copy': typeof import('./src/components/page/Board/Notice/FirstNoticeDetail copy.vue')['default']
    FirstNoticeMain: typeof import('./src/components/page/Board/Notice/FirstNoticeMain.vue')['default']
    'FirstNoticeMain copy': typeof import('./src/components/page/Board/Notice/FirstNoticeMain copy.vue')['default']
    FirstNoticeSearch: typeof import('./src/components/page/Board/Notice/FirstNoticeSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeModal: typeof import('./src/components/page/Board/Notice/NoticeModal.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
