export const Resume = {
  ListResume: "/api/apply/resumeListBody.do",
  CopyResume: "/api/apply/resumeCopyBody.do",
  DeleteResume: "/api/apply/resumeDeleteBody.do",
  BasicInfoResume: "/api/apply/resumeNew.do",
  SaveResume: "/api/apply/resumeSaveBody.do",
  PreviewResume: "/api/apply/previewResumeBody.do",
  MyResume: "/api/apply/resumeDetail.do",
  MainResume: "/api/apply/mainResume.do",
  MainResumeDetail: "/api/apply/mainResumeDetail.do",
  FileDownAtt: "/api/apply/AttachmentFileDownload.do",
  // GetProfileimg: "/api/apply/resumeFileDownload.do",
  GetProfileimg: "/api/apply/resumeFileDownload.do",
};

export const ResumeAddTable = {
  InsertCareer: "/api/apply/insertCareerBody.do",
  ListCareer: "/api/apply/careerListBody.do",
  DeleteCareer: "/api/apply/deleteCareerBody.do",
  InsertEducation: "/api/apply/insertEduBody.do",
  ListEducation: "/api/apply/eduListBody.do",
  DeleteEducation: "/api/apply/deleteEduBody.do",
  InsertSkill: "/api/apply/insertSkillBody.do",
  ListSkill: "/api/apply/skillListBody.do",
  DeleteSkill: "/api/apply/deleteSkillBody.do",
  InsertCertification: "/api/apply/insertCertBody.do",
  ListCertification: "/api/apply/certListBody.do",
  DeleteCertification: "/api/apply/deleteCertBody.do",
  DeleteAttachFile: "/api/apply/deleteAttachFile.do",
  InsertAttachment: "/api/apply/attachmentSaveBody.do",
  ListAttachment: "/api/apply/attachmentListBody.do",
  DeleteAttachment: "/api/apply/deleteAttachmentBody.do",
};
